name: Standard pipeline
run-name: ${{ gitea.actor }}
on:
  - push

jobs:
  build-wishes-qt:
    runs-on: qtcontainer-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compile
        run: |
          mkdir -p "${{ gitea.workspace }}/build"
          cd "${{ gitea.workspace }}/build"
          cmake .. -DCMAKE_COLOR_DIAGNOSTICS=ON -DCMAKE_COLOR_MAKEFILE=ON
          cmake --build . -j9 
