name: Gitea Actions Test
run-name: ${{ gitea.actor }} testing
on: [push]

jobs:
  build-wishes-qt:
    runs-on: qtcontainer-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compile
        run: |
          mkdir -p "${{ gitea.workspace }}/build"
          cd "${{ gitea.workspace }}/build"
          cmake .. -DCMAKE_COLOR_DIAGNOSTICS=ON -DCMAKE_COLOR_MAKEFILE=ON
          make -j7
