name: Gitea Actions Test
run-name: ${{ gitea.actor }} testing
on: [push]

jobs:
  build-wishes-qt:
    runs-on: wishes-qtcontainer-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          find ${{ gitea.workspace }} -type f
      - run: |
          mkdir -p "${{ gitea.workspace }}"/build
      - run: |
          cd ""${{ gitea.workspace }}/build"
          cmake ..
          make -j7
