name: Gitea Actions Test
run-name: ${{ gitea.actor }} testing
on: [push]

jobs:
  build-wishes-qt:
    runs-on: qtcontainer-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: List files in the repository
        run: |
          find ${{ gitea.workspace }} -type f
      - name: Create workspace
        run: |
          mkdir -p "${{ gitea.workspace }}/build"
      - name: Compile
        run: |
          cd "${{ gitea.workspace }}/build"
          cmake ..
          make -j7
